id: A03163CF1
title: Verses of the Eight Noble Auspicious Ones
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:52:48.431542
  last_modified_at: 2022-03-01 02:52:48.431545
