id: A03163CF1
title: Verses of Auspiciousness
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:52:48.427409
  last_modified_at: 2022-03-01 02:52:48.427412
