id: A03163CF1
title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness and Wellbeing'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:52:48.433359
  last_modified_at: 2022-03-01 02:52:48.433362
