id: A03163CF1
title: A Prayer for Auspiciousness
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:52:48.422704
  last_modified_at: 2022-03-01 02:52:48.422710
